language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - npm install -g now
install:
  - yarn install
script:
  - yarn eslint src
  - yarn build
deploy:  
  - provider: script
    skip_cleanup: true
    script: .travis/deploy-now.sh